version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 846208223569.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t testimages:latest nginx/.
      - docker tag testimages:latest 846208223569.dkr.ecr.us-east-1.amazonaws.com/testimages:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 846208223569.dkr.ecr.us-east-1.amazonaws.com/testimages:latest